add : cnn model with cinic lance image dataset
lancedb/lance-deeplearning-recipes pull request #12
Opened 2024-04-19 09:39 UTC by vipul-maheshwari

@AyushExel @tanaymeh

2024-04-21 00:39 UTC, AyushExel commented on community-examples/README.md
> +Today we are going to demonstrate how to train a Convolutional Neural Network (CNN) model using the CINIC-10 image dataset in the Lance format. The [CINIC-10](https://paperswithcode.com/dataset/cinic
"This example demonstrates how to train ..."

2024-04-21 00:48 UTC, AyushExel commented
<img width="552" alt="Screenshot 2024-04-21 at 6 16 18 " src="https://github.com/lancedb/lance-deeplearning-recipes/assets/15766192/2f8a35bf-27e1-4177-a6e3-bcd08739c7ac">
@vipul-maheshwari I think converting to df and operating on it is not necessary here. Instead just accept the path of the lance dataset, load it on initialisation and when called while training/validating just read the batch with offset?

2024-04-22 13:09 UTC, AyushExel approved these changes

2024-04-22 15:15 UTC, tanaymeh commented
Why is the model accuracy at 15% @vipul-maheshwari?

And the loss is barely decreasing over the epochs which doesn't really show the point. Can you improve the model?

2024-04-22 15:20 UTC, tanaymeh requested changes
Please improve the training and testing accuracy and make sure the loss decreases.

2024-04-22 19:29 UTC, vipul-maheshwari commented
The main goal for using lance image dataset to train a CNN model is to understand how using lance dataloader over vanilla dataloader can improve the time it takes to train one epoch, I have a report ready by the tomorrow to clarify more about this comparison.. 

tldr : The same script with lance dataloaders are taking almost half the time to train over an epoch as compared to the vanilla ones.. LANCE IS SPEEDY AS HELL 🚀

2024-04-23 08:27 UTC, tanaymeh approved these changes

2024-04-25 01:35 UTC, AyushExel commented
<img width="869" alt="Screenshot 2024-04-25 at 7 02 21 AM" src="https://github.com/lancedb/lance-deeplearning-recipes/assets/15766192/1ea9b135-e111-4ab1-88bb-e52cabade809">
@vipul-maheshwari `to_table()` turns lance dataset into pyarrow table, which is not lance format. 
The flow is to be something like this:
* DataLoader accepts lance dataset
* In the constructor you just load the lance dataset using lance.dataset(path)
* when getitem is called you simply access the data from lance format on that index
See this section from the docs - https://lancedb.github.io/lance/read_and_write.html#reading-lance-dataset
<img width="878" alt="Screenshot 2024-04-25 at 7 04 52 AM" src="https://github.com/lancedb/lance-deeplearning-recipes/assets/15766192/c1fee5fc-ea47-4070-b479-8b3f3398011e">

2024-04-25 08:35 UTC, merged